name: Test and build

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 
          - 14.x

    steps:
      - name: Checkouting code...
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM install
        run: npm install

      - name: NPM build
        run: npm run build

      - name: NPM format
        run: npm run format

      - name: NPM format check
        run: npm run format-check

      - name: Lint
        run: npm run lint

      - name: Pack
        run: npm run pack

  commit_and_push:

    runs-on: ubuntu-latest
    name: Commit and push build if needed
    needs: build

    steps:
      -
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatically builded and updated
          file_pattern: dist/*.js
          skip_fetch: true
          skip_checkout: true