name: Tests and Checks

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  test:
    name: Run Bats Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install Bats
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.8.2

      - name: Run Bats Tests
        run: bats tests
